In [15]:
import pandas as pd

In [16]:
df=pd.read_csv('ORCR_16_22_all.csv')
df

,Unnamed: 0,Institute,Academic Program Name,Quota,Seat Type,Gender,Opening Rank,Closing Rank,Year,Round
0,0,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OPEN,NaN,3533.0,5947.0,2016,1
1,1,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,OBC-NCL,NaN,1829.0,2213.0,2016,1
2,2,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,SC,NaN,663.0,1023.0,2016,1
3,3,Indian Institute of Technology Bhubaneswar,"Civil Engineering (4 Years, Bachelor of Techno...",AI,ST,NaN,331.0,357.0,2016,1
4,4,Indian Institute of Technology Bhubaneswar,Civil Engineering and M. Tech. in Structural E...,AI,OPEN,NaN,5408.0,6561.0,2016,1
...,...,...,...,...,...,...,...,...,...,...
89431,89431,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,OBC-NCL,Female-only (including Supernumerary),7459,8884,2022,6
89432,89432,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,SC,Gender-Neutral,1709,2379,2022,6
89433,89433,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,SC,Female-only (including Supernumerary),3122,3122,2022,6
89434,89434,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,ST,Gender-Neutral,1044,1095,2022,6
89435,89435,Indian Institute of Technology Dharwad,"Mechanical Engineering (4 Years, Bachelor of T...",AI,ST,Female-only (including Supernumerary),1389,1389,2022,6

In [17]:
institutes=df["Institute"].unique()
branches=df["Academic Program Name"].unique()
quota=df["Quota"].unique()
seat=df["Seat Type"].unique()
gender=df["Gender"].unique()
orank=df["Opening Rank"].unique()
crank=df["Closing Rank"].unique()
year=df["Year"].unique()
round=df["Round"].unique()

In [61]:

print(seat)

['OPEN' 'OBC-NCL' 'SC' 'ST' 'OPEN (PwD)' 'OBC-NCL (PwD)' 'SC (PwD)'
 'ST (PwD)' 'EWS' 'EWS (PwD)']

In [62]:
with open('allbranch.txt','w') as file:
    file.write('\n'.join(branches))
with open('allinstitutes.txt','w') as file:
    file.write('\n'.join(institutes))

with open('allseat.txt','w') as file:
    file.write('\n'.join(seat))
# with open('allor.txt','w') as file:
#     file.write('\n'.join(orank))
# with open('allcr.txt','w') as file:
#     file.write('\n'.join(crank))

with open('allquota.txt','w') as file:
    for qt in quota:
        file.write(str(qt)+'\n')
with open('allyear.txt','w') as file:
    for yr in year:
        file.write(str(yr)+'\n')

with open('allround.txt','w') as file:
    for rnd in round:
        file.write(str(rnd)+'\n')

with open('allgender.txt','w') as file:
    for gen in gender:
        file.write(str(gen)+'\n')